export const TOOLTIP_POSITION = {
  START: 'start',
  END: 'end',
  TOP: 'top',
  BOTTOM: 'bottom',
} as const;

export const DEFAULT_TOOLTIP_POSITION = TOOLTIP_POSITION.END;

export const OPPOSITE_POSITION = {
  [TOOLTIP_POSITION.START]: TOOLTIP_POSITION.END,
  [TOOLTIP_POSITION.END]: TOOLTIP_POSITION.START,
  [TOOLTIP_POSITION.TOP]: TOOLTIP_POSITION.BOTTOM,
  [TOOLTIP_POSITION.BOTTOM]: TOOLTIP_POSITION.TOP,
};

export const CONTENT_DIMENSION = {
  [TOOLTIP_POSITION.START]: 'width',
  [TOOLTIP_POSITION.END]: 'width',
  [TOOLTIP_POSITION.TOP]: 'height',
  [TOOLTIP_POSITION.BOTTOM]: 'height',
} as const;
